backend/config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  # Session routes
  get "sign-in", to: "sessions#new", as: :sign_in
  post "sign-in", to: "sessions#create"
  get "sign-out", to: "sessions#destroy", as: :sign_out

  resources :entries do
    collection do
      get "upload", to: "ofx_uploads#new"
      post "upload", to: "ofx_uploads#create"
    end
  end
  resources :buckets, except: [ :destroy ]

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "buckets#index"
end

backend/app/models/bucket.rb
class Bucket < ApplicationRecord
  belongs_to :account

  has_many :debits, class_name: "Entry", foreign_key: :debit_account_id
  has_many :credits, class_name: "Entry", foreign_key: :credit_account_id

  after_initialize :set_defaults

  enum :account_type, { income: "Income", spending: "Spending", real: "Real" }

  def balance
    d = debits.map { |e| e.amount }.sum
    c = credits.map { |e| e.amount }.sum

    virtual? ? c - d : d - c
  end

  def virtual?
    income? || spending?
  end

  private

  def set_defaults
    self.account_type ||= :spending
  end
end

backend/app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :must_be_signed_in
  before_action :set_bucket, only: %i[ show edit update ]

  def index
    filter = params[:type]

    @buckets = filter.nil? ?
      current_account.custom_buckets :
      current_account.custom_buckets.where(account_type: filter.to_sym)
  end

  def show
    @entries = Entry.where(debit_account_id: @bucket.id).or(Entry.where(credit_account_id: @bucket.id))
  end

  def new
    @bucket = Bucket.new account_id: current_account.id
  end

  def edit
  end

  def create
    @bucket = Bucket.new bucket_params.merge(account_id: current_account.id)

    respond_to do |format|
      if @bucket.save
        format.html { redirect_to buckets_path, notice: "Bucket was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bucket.update(bucket_params)
        format.html { redirect_to buckets_path, notice: "Bucket was successfully updated.", status: :see_other }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end


  private

  def set_bucket
    @bucket = Bucket.find(params.expect(:id))
  end

  def bucket_params
    params.expect(bucket: [ :name, :description, :account_type ])
  end
end

backend/app/helpers/buckets_helper.rb
module BucketsHelper
end

backend/app/views/buckets/_form.html.erb
<%= form_with(model: bucket) do |form| %>
  <% if bucket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bucket.errors.count, "error") %> prohibited this bucket from being saved:</h2>

      <ul>
        <% bucket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :account_type, style: "display: block" %>
    <%= form.select :account_type, Bucket.account_types.collect { |k,v| [v, k]} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/buckets/edit.html.erb
<div class="breadcrumbs"><%= link_to "Buckets", buckets_path %> > <%= @bucket.name %></div>

<p style="color: green"><%= notice %></p>
<br>

<h1>Edit Your Bucket</h1>

<%= render "form", bucket: @bucket %>

backend/app/views/buckets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Buckets</h1>
<p><%= link_to "New bucket", new_bucket_path %></p>

<br>
<div>
  <%= link_to "All", buckets_path %>
  <%= link_to "Income", buckets_path(type: :income) %>
  <%= link_to "Spending", buckets_path(type: :spending) %>
  <%= link_to "Bank Accounts", buckets_path(type: :real) %>
</div>
<br>

<div class="bucket-list">
  <% @buckets.each do |bucket| %>
    <a href="<%= bucket_path(bucket) %>" class="card flex-down">
    <div class="flex-right space-between">
      <h1 class="play"><%= bucket.name %></h1>
      <div class="play"><%= number_to_currency bucket.balance %></div>
    </div>
    <div class="flex-right space-between">
      <div><%= bucket.description %></div>
      <div>#<%= bucket.account_type %></div>
    </div>
    </a>
  <% end %>
</div>

backend/app/views/buckets/new.html.erb
<% content_for :title, "New bucket" %>

<h1>New bucket</h1>

<%= render "form", bucket: @bucket %>

<br>

<div>
  <%= link_to "Back to buckets", buckets_path %>
</div>

backend/app/views/buckets/show.html.erb
<div class="breadcrumbs"><%= link_to "Buckets", buckets_path %> > <%= @bucket.name %></div>

<p style="color: green"><%= notice %></p>
<br>

<div id="<%= dom_id @bucket %>" class="flow-down">
  <div class="card">
    <div class="flex-right space-between">
      <h1 class="play"><%= @bucket.name %></h1>
      <div class="play"><%= number_to_currency @bucket.balance %></div>
    </div>
    <div class="flex-right space-between">
      <div><%= @bucket.description %></div>
      <div>#<%= @bucket.account_type %></div>
    </div>
  </div>
</div>

<br>

<div>
  <%= link_to "New Entry", new_entry_path %>
  <%= link_to "Edit", edit_bucket_path(@bucket) %>
</div>

<br>

<%= render "entries/entries", entries: @entries %>